<?php

namespace PersonnesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProfesseurAssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesseurAssociationRepository extends EntityRepository
{
}
