accueil :
    pattern: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    :accueil.html.twig

contact :
    pattern: /contact
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    :contact.html.twig


administration :
    pattern: /administration
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    :administration.html.twig

# mon_compte:
#     pattern: /moncompte
#     defaults:
#         _controller: FrameworkBundle:Template:template
#         template:    :moncompte.html.twig

personnes:
    resource: "@PersonnesBundle/Resources/config/routing.yml"
    #type:     annotation
    prefix:   /

saisons:
    resource: "@SaisonsBundle/Resources/config/routing.yml"
    #~ type:     annotation
    prefix:   /

soirees:
    resource: "@SoireesBundle/Resources/config/routing.yml"
    #~ type:     annotation
    prefix:   /soirees

cours:
    resource: "@CoursBundle/Resources/config/routing.yml"
    #~ type:     annotation
    prefix:   /cours

stages:
    resource: "@StagesBundle/Resources/config/routing.yml"
    #~ type:     annotation
    prefix:   /stages

app:
    resource: "@AppBundle/Controller/"
    type:     annotation



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
