<?php

namespace SaisonsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Forfait_Danse_Niveau_danseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Forfait_Danse_Niveau_danseRepository extends EntityRepository
{
}
