<?php

namespace SaisonsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SallesSaisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SallesSaisonRepository extends EntityRepository
{
}
