<?php

namespace SaisonsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TypeForfaitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeForfaitRepository extends EntityRepository
{
}
