<?php

namespace CoursBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends EntityRepository
{
	// Récupérer les cours pour lesquels un prof de id $idprof enseigne
	public function getCours($idprof){
		//~ $em = $this->getEntityManager()->getConfiguration();
		$qb = $this->createQueryBuilder('c');
		$qb->join('c.professeurAssociation', 'f')
		   ->where($qb->expr()->eq('f.id', $idprof));
		return $qb;
	}
  
  
}
